# Generated by Django 5.0.7 on 2024-07-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsCategory',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('email', models.TextField()),
                ('activity_description', models.TextField()),
                ('image', models.ImageField(default='NoImage.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('date', models.TextField()),
                ('tags', models.TextField()),
                ('author', models.TextField(default='Admin MSDEP 1')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documentscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='')),
                ('date', models.DateField(default='2024-07-10')),
                ('related_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news')),
            ],
        ),
    ]
